title: "&f[&e速建&f]"

scoreboard-title: "&a速建"

# 是否保存玩家背包
save-playerInventory:  true



game-logo: "author: sobadfish "

join-menu:
  cw:
    buttonImg:
      type: "path"
      path: "textures/ui/icon_recipe_item"
    rooms:
      - 测试房间